### ISSUE TITLE
Collapse Sidebar For Mobile

### ISSUE THREAD

**Issue by Harmiox** [pratikborsadiya/vali-admin#28]
**Issue description**
Every time I visit a page on mobile the sidebar is expanded. Shouldn't it be automatically collapsed for mobile devices/small screen sizes?

**Steps to reproduce (if you knew)**
Visit any page on a mobile device view on with a small page width.

**Expected behaviour**
Collapse the sidebar for mobile devices/small screens.

**Other Note (feature-request, question, etc...)**

**Comment by Cali03** [comment]
Issue description
If you have the sidebar toggled and you reduce the page there comes a time when the sidebar is extended.

Steps to reproduce (if you knew)
Toggled the sidebar and reduce the page or toggled the sidebar and with change resolution to mobile.

Expected behaviour
Sidebar stay toggled 

Other Note (feature-request, question, etc...)
