### ISSUE TITLE
Font awesome 5 support?

### ISSUE THREAD

**Issue by 776166** [pratikborsadiya/vali-admin#51]
May be? :)

**Comment by pratikborsadiya** [comment]
Hi @776166 

We had a pull request for the same but unfortunately the creator of the pull request was not able to take it forward.

I am thinking about moving to SVG icons instead of font icons in the future versions, That way you can use any icon font you want and also mix and match them without worrying about performance impact of using multiple font-icon sets.

**Comment by theshaun** [comment]
Hi @776166 and @pratikborsadiya , 

Apologies re last pull request. I have been caught up at work and never got a chance to resolve the last pull.

I'm also looking at the svg version for a separate project, so might investigate unless you have something planned.

**Comment by pratikborsadiya** [comment]
Hi Shaun,

As I mentioned earlier, I am planning to move to SVG icons instead of font based icons in upcoming version of the theme.
